multi image builds (#11)

diff --git a/.devcontainer/nrf-docker/Dockerfile b/.devcontainer/nrf-docker/Dockerfile
--- a/.devcontainer/nrf-docker/Dockerfile
+++ b/.devcontainer/nrf-docker/Dockerfile
@@ -1,11 +1,8 @@
-# Dockerfile from this repository is used to build the image
-# Only difference is that the image is based on devcontainers/base:bullseye for better compatibility with GitHub Codespaces
-# https://github.com/NordicPlayground/nrf-docker
-#FROM mcr.microsoft.com/devcontainers/base:bullseye
-
-FROM tigitlabs/ubuntu-base:latest
-
-WORKDIR /workdir
+# Based on: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/ubuntu
+# nrf-docker
+ARG VARIANT=ubuntu-22.04
+# FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
+FROM ghcr.io/tigitlabs/ubuntu-base
 
 ARG sdk_nrf_branch=v2.4-branch
 ARG toolchain_version=v2.4.1
@@ -13,95 +10,97 @@ ARG sdk_nrf_commit
 ARG NORDIC_COMMAND_LINE_TOOLS_VERSION="10-23-0/nrf-command-line-tools-10.23.0"
 ARG arch=amd64
 
-ENV DEBIAN_FRONTEND=noninteractive
+# Exit immediately if any command fails
+RUN set -e
 
-RUN apt-get -y update && \
+RUN apt-get -y update && export DEBIAN_FRONTEND=noninteractive ; \
     apt-get -y upgrade && \
-    apt-get -y install \
-    wget \
-    unzip \
-    git \
+    apt-get -y install --no-install-recommends \
     python3-pip \
     python3-setuptools \
     python3-wheel \
     python3-dev \
     python3-venv \
-    clang-format
+    clang-format \
+    cmake
 
-# PIP dependencies
-RUN pip install --upgrade pip && \
-    pip install --upgrade setuptools && \
-    pip install install west
+COPY ./entry.sh /root/entry.sh
+
+USER vscode
+RUN sudo chmod +x /root/entry.sh && \
+    sudo chown -R vscode:vscode /root
+
+WORKDIR /workspace
+# ClangFormat
+RUN wget -qO- https://raw.githubusercontent.com/nrfconnect/sdk-nrf/${sdk_nrf_branch}/.clang-format > /workspace/.clang-format
+
+# pip dependecies
+RUN sudo pip install --upgrade pip && \
+    sudo pip install --upgrade setuptools && \
+    sudo pip install west
 
 # Install toolchain
 # Make nrfutil install in a shared location, because when used with GitHub
 # Actions, the image will be launched with the home dir mounted from the local
 # checkout.
-ENV NRFUTIL_HOME=/usr/local/share/nrfutil
 RUN wget -q https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil ; \
-    mv nrfutil /usr/local/bin ; \
-    chmod +x /usr/local/bin/nrfutil ; \
-    nrfutil install toolchain-manager ; \
+    sudo mv nrfutil /usr/local/bin ; \
+    sudo chmod +x /usr/local/bin/nrfutil ; \
+    sudo nrfutil install toolchain-manager ; \
     nrfutil install toolchain-manager search ; \
     nrfutil toolchain-manager install --ncs-version ${toolchain_version} ; \
     nrfutil toolchain-manager list
 
-# ClangFormat
-#
-RUN wget -qO- https://raw.githubusercontent.com/nrfconnect/sdk-nrf/${sdk_nrf_branch}/.clang-format > /workdir/.clang-format
-
 # Nordic command line tools
 # Releases: https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools/download
-RUN NCLT_BASE=https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/desktop-software/nrf-command-line-tools/sw/versions-10-x-x ; \
-    echo "Host architecture: $arch" ; \
-    case $arch in \
-        "amd64") \
-            NCLT_URL="${NCLT_BASE}/${NORDIC_COMMAND_LINE_TOOLS_VERSION}_linux-amd64.tar.gz" ;; \
-        "arm64") \
-            NCLT_URL="${NCLT_BASE}/${NORDIC_COMMAND_LINE_TOOLS_VERSION}_linux-arm64.tar.gz" ;; \
-    esac ; \
-    echo "NCLT_URL=${NCLT_URL}" ; \
-    if [ ! -z "$NCLT_URL" ] ; then \
-        echo "Installing nRF Command Line Tools" ; \
-        mkdir tmp && cd tmp ; \
-        wget -qO - "${NCLT_URL}" | tar --no-same-owner -xz ; \
-        # Install included JLink
-        mkdir /opt/SEGGER ; \
-        tar xzf JLink_*.tgz -C /opt/SEGGER ; \
-        mv /opt/SEGGER/JLink* /opt/SEGGER/JLink ; \
-        # Install nrf-command-line-tools
-        cp -r ./nrf-command-line-tools /opt ; \
-        ln -s /opt/nrf-command-line-tools/bin/nrfjprog /usr/local/bin/nrfjprog ; \
-        ln -s /opt/nrf-command-line-tools/bin/mergehex /usr/local/bin/mergehex ; \
-        cd .. && rm -rf tmp ; \
-        nrfutil help ; \
-    else \
-        echo "Skipping nRF Command Line Tools (not available for $arch)" ; \
-        exit 1 ; \
-    fi
+RUN <<EOT
+    NCLT_BASE=https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/desktop-software/nrf-command-line-tools/sw/versions-10-x-x
+    NCLT_URL="${NCLT_BASE}/${NORDIC_COMMAND_LINE_TOOLS_VERSION}_linux-amd64.tar.gz"
+    mkdir tmp && cd tmp
+    wget -qO - "${NCLT_URL}" | tar --no-same-owner -xz
+    # Install nrf-command-line-tools
+    sudo cp -r ./nrf-command-line-tools /opt
+    sudo ln -s /opt/nrf-command-line-tools/bin/nrfjprog /usr/local/bin/nrfjprog
+    sudo ln -s /opt/nrf-command-line-tools/bin/mergehex /usr/local/bin/mergehex
+    # Install included JLink
+    sudo mkdir /opt/SEGGER
+    sudo tar xzf JLink_*.tgz -C /opt/SEGGER
+    sudo mv /opt/SEGGER/JLink* /opt/SEGGER/JLink
+    cd .. && rm -rf tmp ;
+EOT
 
 # Prepare image with a ready to use build environment
-SHELL ["nrfutil","toolchain-manager","launch","/bin/bash","--","-c"]
-
-RUN west init -m https://github.com/nrfconnect/sdk-nrf --mr ${sdk_nrf_branch} . ; \
-    if [[ $sdk_nrf_commit =~ "^[a-fA-F0-9]{32}$" ]] ; \
-    then \
-        git checkout ${sdk_nrf_commit} ; \
-    fi ; \
+# SHELL ["nrfutil","toolchain-manager","launch","/bin/bash","--","-c"]
+RUN <<EOT
+    west init -m https://github.com/nrfconnect/sdk-nrf --mr ${sdk_nrf_branch} /workspace
+    if [[ $sdk_nrf_commit =~ "^[a-fA-F0-9]{32}$" ]]; then
+        git checkout ${sdk_nrf_commit};
+    fi
     west update --narrow -o=--depth=1
+EOT
 
-COPY ./entry.sh /root/entry.sh
-RUN chmod +x /root/entry.sh
+ENV ZEPHYR_BASE=/workspace/zephyr \
+    ZEPHYR_TOOLCHAIN_VARIANT=zephyr \
+    ZEPHYR_SDK_INSTALL_DIR=/home/vscode/ncs/toolchains/1f9b40e71a/opt/zephyr-sdk \
+    GIT_EXEC_PATH=/home/vscode/ncs/toolchains/1f9b40e71a/usr/local/libexec/git-core \
+    GIT_TEMPLATE_DIR=/home/vscode/ncs/toolchains/1f9b40e71a/usr/local/share/git-core/templates \
+    NRFUTIL_LAUNCHER_VERSION=1.0.0 \
+    NRFUTIL_TOOLCHAIN_MANAGER_CURRENT_TOOLCHAIN=${toolchain_version} \
+    NRFUTIL_EXEC_PATH=/home/vscode/.nrfutil/bin/nrfutil \
+    PYTHONPATH=/home/vscode/ncs/toolchains/1f9b40e71a/usr/local/lib/python3.8/site-packages \
+    PYTHONHOME=/home/vscode/ncs/toolchains/1f9b40e71a/usr/local
 
-# Adding permission to non-root user from the the base image
-ARG USERNAME=vscode
-ARG USER_UID=1000
-ARG USER_GID=$USER_UID
-RUN chown -R $USERNAME:$USER_GID /root/ \
-    && chown -R $USERNAME:$USER_GID /workdir/ \
-    && chown -R $USERNAME:$USER_GID $NRFUTIL_HOME
+ENV LD_LIBRARY_PATH="/home/vscode/ncs/toolchains/1f9b40e71a/usr/lib:\
+/home/vscode/ncs/toolchains/1f9b40e71a/usr/lib/x86_64-linux-gnu:\
+/home/vscode/ncs/toolchains/1f9b40e71a/usr/local/lib:\
+/home/vscode/.nrfutil/lib/nrfutil-toolchain-manager:${LD_LIBRARY_PATH}}"
 
-# Launch into build environment with the passed arguments
-# Currently this is not supported in GitHub Actions
-# See https://github.com/actions/runner/issues/1964
-ENTRYPOINT [ "nrfutil", "toolchain-manager", "launch", "/bin/bash", "--", "/root/entry.sh" ]
+ENV PATH="/home/vscode/ncs/toolchains/1f9b40e71a/usr/bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/usr/bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/usr/local/bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/opt/bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/opt/nanopb/generator-bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/opt/zephyr-sdk/aarch64-zephyr-elf/bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/opt/zephyr-sdk/x86_64-zephyr-elf/bin:\
+/home/vscode/ncs/toolchains/1f9b40e71a/opt/zephyr-sdk/arm-zephyr-eabi/bin:\
+/workspace/zephyr/scripts:${PATH}"
